# Generated by Django 2.0.2 on 2019-01-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calipsoexperiment',
            old_name='serial_number',
            new_name='proposal_id',
        ),
        migrations.RenameField(
            model_name='historicalcalipsoexperiment',
            old_name='serial_number',
            new_name='proposal_id',
        ),
    ]
