# Generated by Django 2.0.2 on 2018-04-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuacamoleConnection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=128)),
                ('protocol', models.CharField(max_length=32)),
                ('proxy_port', models.IntegerField(blank=True, null=True)),
                ('proxy_hostname', models.CharField(blank=True, max_length=512, null=True)),
                ('proxy_encryption_method', models.CharField(blank=True, max_length=4, null=True)),
                ('max_connections', models.IntegerField(blank=True, null=True)),
                ('max_connections_per_user', models.IntegerField(blank=True, null=True)),
                ('connection_weight', models.IntegerField(blank=True, null=True)),
                ('failover_only', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'guacamole_connection',
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionGroup',
            fields=[
                ('connection_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_group_name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=14)),
                ('max_connections', models.IntegerField(blank=True, null=True)),
                ('max_connections_per_user', models.IntegerField(blank=True, null=True)),
                ('enable_session_affinity', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'guacamole_connection_group',
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=128)),
                ('parameter_value', models.CharField(max_length=4096)),
            ],
            options={
                'managed': False,
                'db_table': 'guacamole_connection_parameter',
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'guacamole_connection_permission',
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password_hash', models.BinaryField()),
                ('password_salt', models.BinaryField(blank=True, null=True)),
                ('password_date', models.DateTimeField()),
                ('disabled', models.IntegerField()),
                ('expired', models.IntegerField()),
                ('access_window_start', models.TimeField(blank=True, null=True)),
                ('access_window_end', models.TimeField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email_address', models.CharField(blank=True, max_length=256, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('organizational_role', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'guacamole_user',
            },
        ),
        migrations.CreateModel(
            name='CalipsoContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calipso_user', models.CharField(max_length=255)),
                ('calipso_experiment', models.CharField(max_length=255)),
                ('container_id', models.CharField(max_length=255)),
                ('container_name', models.CharField(max_length=255)),
                ('container_status', models.CharField(max_length=25)),
                ('container_info', models.TextField()),
                ('container_logs', models.TextField()),
            ],
            options={
                'db_table': 'calipso_containers',
            },
        ),
        migrations.CreateModel(
            name='CalipsoExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'calipso_experiments',
            },
        ),
        migrations.CreateModel(
            name='CalipsoFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=2083)),
            ],
            options={
                'db_table': 'calipso_facilities',
            },
        ),
        migrations.CreateModel(
            name='CalipsoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calipso_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('experiments', models.ManyToManyField(to='apprest.CalipsoExperiment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calipso_users',
            },
        ),
    ]
