# Generated by Django 2.0.2 on 2018-04-12 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalipsoContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('container', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=15)),
                ('calipso_user', models.ManyToManyField(to='apprest.CalipsoUser')),
            ],
            options={
                'db_table': 'calipso_containers',
            },
        ),
    ]
