# Generated by Django 2.0.2 on 2019-02-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_auto_20190123_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalipsoResourcesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'calipso_resource_types',
            },
        ),
        migrations.AddField(
            model_name='calipsoavailableimages',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoResourcesType'),
        ),
        migrations.AddField(
            model_name='historicalcalipsoavailableimages',
            name='resource_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apprest.CalipsoResourcesType'),
        ),
    ]
