# Generated by Django 2.0.2 on 2018-07-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalipsoUserExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('calipso_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoExperiment')),
            ],
            options={
                'db_table': 'calipso_user_experiment',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCalipsoUserExperiment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calipso_experiment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apprest.CalipsoExperiment')),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical calipso user experiment',
            },
        ),
        migrations.RemoveField(
            model_name='calipsouser',
            name='experiments',
        ),
        migrations.AlterField(
            model_name='calipsouserquota',
            name='cpu',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='calipsouserquota',
            name='hdd',
            field=models.CharField(default='80G', max_length=100),
        ),
        migrations.AlterField(
            model_name='calipsouserquota',
            name='max_simultaneous',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='calipsouserquota',
            name='memory',
            field=models.CharField(default='30G', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcalipsouserquota',
            name='cpu',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='historicalcalipsouserquota',
            name='hdd',
            field=models.CharField(default='80G', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcalipsouserquota',
            name='max_simultaneous',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='historicalcalipsouserquota',
            name='memory',
            field=models.CharField(default='30G', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcalipsouserexperiment',
            name='calipso_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apprest.CalipsoUser'),
        ),
        migrations.AddField(
            model_name='historicalcalipsouserexperiment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calipsouserexperiment',
            name='calipso_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoUser'),
        ),
        migrations.AddField(
            model_name='calipsoexperiment',
            name='calipso_users',
            field=models.ManyToManyField(through='apprest.CalipsoUserExperiment', to='apprest.CalipsoUser'),
        ),
    ]
