# Generated by Django 2.0.2 on 2018-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calipsocontainer',
            name='max_num_container',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='historicalcalipsocontainer',
            name='max_num_container',
            field=models.IntegerField(default=3),
        ),
    ]
