# Generated by Django 2.0.2 on 2019-02-05 14:36
import logging

from django.db import migrations

from apprest.utils.migrations import create_resources_types

logger = logging.getLogger(__name__)


def my_function(apps, schema_editor):
    # logger.debug('apps = %s, schema_editor = %s' % (apps, schema_editor))
    create_resources_types()


class Migration(migrations.Migration):
    dependencies = [
        ('apprest', '0002_auto_20190206_1317'),
    ]

    operations = [migrations.RunPython(my_function)]
