# Generated by Django 2.0.2 on 2018-04-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0002_calipsocontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calipsocontainer',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='calipsocontainer',
            name='calipso_user',
        ),
        migrations.AddField(
            model_name='calipsocontainer',
            name='calipso_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoUser'),
        ),
    ]
