# Generated by Django 2.0.2 on 2018-10-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0003_populate_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calipsouserquota',
            name='cpu',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='calipsouserquota',
            name='max_simultaneous',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='historicalcalipsouserquota',
            name='cpu',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='historicalcalipsouserquota',
            name='max_simultaneous',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='calipsouserexperiment',
            unique_together={('calipso_user', 'calipso_experiment')},
        ),
    ]
