# Generated by Django 2.0.2 on 2018-06-07 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0003_auto_20180607_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='calipsocontainer',
            name='host_port',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcalipsocontainer',
            name='host_port',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='calipsocontainer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcalipsocontainer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
