# Generated by Django 2.0.2 on 2018-04-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0003_auto_20180412_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='calipsocontainer',
            name='calipso_experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoExperiment'),
        ),
        migrations.AlterUniqueTogether(
            name='calipsocontainer',
            unique_together={('calipso_user', 'calipso_experiment')},
        ),
    ]
