# Generated by Django 2.0.2 on 2018-04-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0004_auto_20180412_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calipsocontainer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='calipsocontainer',
            name='calipso_experiment',
        ),
        migrations.RemoveField(
            model_name='calipsocontainer',
            name='calipso_user',
        ),
        migrations.DeleteModel(
            name='CalipsoContainer',
        ),
    ]
