# Generated by Django 2.0.2 on 2019-02-11 10:43

from django.db import migrations

from apprest.utils.migrations import create_static_link


def my_function(apps, schema_editor):
    create_static_link()


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0004_populate_images'),
    ]

    operations = [migrations.RunPython(my_function)]

