# Generated by Django 2.0.2 on 2019-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0005_populate_static_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='calipsoexperiment',
            name='gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calipsoexperiment',
            name='uid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcalipsoexperiment',
            name='gid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcalipsoexperiment',
            name='uid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
