# Generated by Django 2.0.2 on 2018-06-07 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0005_auto_20180607_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calipsocontainer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='historicalcalipsocontainer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
