# Generated by Django 2.0.2 on 2018-04-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0005_auto_20180412_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalipsoContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=15)),
                ('calipso_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoExperiment')),
                ('calipso_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoUser')),
            ],
            options={
                'db_table': 'calipso_containers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='calipsocontainer',
            unique_together={('calipso_user', 'calipso_experiment')},
        ),
    ]
