# Generated by Django 2.0.2 on 2018-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0006_auto_20180607_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calipsocontainer',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalcalipsocontainer',
            name='creation_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
