# Generated by Django 2.0.2 on 2018-06-07 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0007_auto_20180607_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calipsocontainer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcalipsocontainer',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
