# Generated by Django 2.1.3 on 2020-01-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0008_auto_20190520_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calipsocontainer',
            name='calipso_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.CalipsoUser'),
        ),
        migrations.AlterField(
            model_name='historicalcalipsocontainer',
            name='calipso_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apprest.CalipsoUser'),
        ),
    ]
